#!/usr/bin/env python3

import sys
import html5lib
import argparse
import re


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input-file')
    args, rest = parser.parse_known_args()
    if args.input_file:
        with open(args.input_file, 'rb') as fp:
            doc = html5lib.parse(fp.read())
    else:
        doc = html5lib.parse(sys.stdin.read())

    NS = dict(h='http://www.w3.org/1999/xhtml')

    def find(path):
        mo = re.match(r'^(.*)/@(\w+)$', path)
        if mo:
            return find(mo.group(1)).attrib[mo.group(2)]
        return doc.find(path, NS)

    for p in rest:
        o = find(p)
        try:
            itertext = o.itertext()
        except AttributeError:
            pass
        else:
            o = ' '.join(''.join(itertext).split())
        print(o)


if __name__ == '__main__':
    main()
